-- Magnitude Analysis
-- Total customers by countries
SELECT country, COUNT(*)
FROM gold.dim_customers dc
GROUP BY country;

-- Total customers by gender
SELECT gender, COUNT(*)
FROM gold.dim_customers dc
GROUP BY gender;

-- Total products by category
SELECT category, COUNT(*)
FROM gold.dim_products dp
GROUP BY category;

-- Average costs in each category
SELECT category, AVG(cost)
FROM gold.dim_products dp
GROUP BY category;

-- Total revenue generated by each category
SELECT p.category, SUM(t.sales_amount)
FROM gold.dim_products p
LEFT JOIN gold.fact_sales t
    ON p.product_key = t.product_key
GROUP BY p.category
UNION ALL
SELECT 'Total', SUM(t.sales_amount)
FROM gold.dim_products p
LEFT JOIN gold.fact_sales t
    ON p.product_key = t.product_key;

-- Total revenue generated by each customer
SELECT c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount)
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY SUM(f.sales_amount) DESC;

-- Total distribution of sold items across countries
SELECT dc.country, SUM(t.quantity)
FROM gold.fact_sales t
LEFT JOIN gold.dim_customers dc
    ON t.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY SUM(t.sales_amount) DESC;
