-- Exploratory Data Analysis (EDA)

----------------------------------------
-- Database Exploration
------------------------------------------
SELECT * FROM gold.dim_customers;
SELECT * FROM gold.fact_sales t;
SELECT * FROM gold.dim_products dp;

--------------------------------------------
-- Dimensions Exploration
---------------------------------------
SELECT MIN(birthdate) AS old_customer, MAX(birthdate) AS latest_customer,
       EXTRACT(YEAR FROM AGE(CURRENT_DATE, MIN(birthdate))) AS age
FROM gold.dim_customers dc;

SELECT COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales t;

SELECT COUNT(DISTINCT product_id) AS total_products
FROM gold.dim_products dp;

SELECT COUNT(DISTINCT product_key) AS sold_products
FROM gold.fact_sales t;

SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers dc;

SELECT COUNT(DISTINCT customer_key) AS active_customers
FROM gold.fact_sales t;

SELECT product_key
FROM gold.dim_products dp
WHERE product_key NOT IN (
    SELECT product_key
    FROM gold.fact_sales t
);

-- 03_date_range_exploration.sql
-- Date Range Exploration
SELECT MIN(birthdate) AS old_customer, MAX(birthdate) AS latest_customer
FROM gold.dim_customers dc;

-- 04_measures_exploration.sql
-- Measures Exploration
SELECT SUM(sales_amount) AS total_sales
FROM gold.fact_sales t;

SELECT SUM(quantity) AS total_quantity
FROM gold.fact_sales t;

SELECT AVG(price) AS average_price
FROM gold.fact_sales t;

-- Report
SELECT 'Total sales' AS measure_name, SUM(sales_amount) AS measure_value
FROM gold.fact_sales t
UNION ALL
SELECT 'Total Quantity', SUM(quantity)
FROM gold.fact_sales t
UNION ALL
SELECT 'Average Price', AVG(price)
FROM gold.fact_sales t
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number)
FROM gold.fact_sales t
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_id)
FROM gold.dim_products dp
UNION ALL
SELECT 'Total customers', COUNT(DISTINCT customer_key)
FROM gold.fact_sales t;


-- Magnitude Analysis
-- Total customers by countries
SELECT country, COUNT(*)
FROM gold.dim_customers dc
GROUP BY country;

-- Total customers by gender
SELECT gender, COUNT(*)
FROM gold.dim_customers dc
GROUP BY gender;

-- Total products by category
SELECT category, COUNT(*)
FROM gold.dim_products dp
GROUP BY category;

-- Average costs in each category
SELECT category, AVG(cost)
FROM gold.dim_products dp
GROUP BY category;

-- Total revenue generated by each category
SELECT p.category, SUM(t.sales_amount)
FROM gold.dim_products p
LEFT JOIN gold.fact_sales t
    ON p.product_key = t.product_key
GROUP BY p.category
UNION ALL
SELECT 'Total', SUM(t.sales_amount)
FROM gold.dim_products p
LEFT JOIN gold.fact_sales t
    ON p.product_key = t.product_key;

-- Total revenue generated by each customer
SELECT c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount)
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY SUM(f.sales_amount) DESC;

-- Total distribution of sold items across countries
SELECT dc.country, SUM(t.quantity)
FROM gold.fact_sales t
LEFT JOIN gold.dim_customers dc
    ON t.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY SUM(t.sales_amount) DESC;


-- Ranking Analysis
-- Top 5 products generating high revenue
SELECT *
FROM (
    SELECT dp.product_number, dp.product_name, SUM(t.sales_amount),
           DENSE_RANK() OVER(ORDER BY SUM(t.sales_amount) DESC) AS rnk
    FROM gold.fact_sales t
    LEFT JOIN gold.dim_products dp
        ON t.product_key = dp.product_key
    GROUP BY dp.product_number, dp.product_name
) t
WHERE rnk < 6;

-- Alternative
SELECT dp.product_number, dp.product_name, SUM(t.sales_amount)
FROM gold.fact_sales t
LEFT JOIN gold.dim_products dp
    ON t.product_key = dp.product_key
GROUP BY dp.product_number, dp.product_name
ORDER BY SUM(t.sales_amount) DESC
LIMIT 5;

-- 5 worst performing products
SELECT *
FROM (
    SELECT dp.product_number, dp.product_name, SUM(t.sales_amount),
           DENSE_RANK() OVER(ORDER BY SUM(t.sales_amount)) AS rnk
    FROM gold.fact_sales t
    LEFT JOIN gold.dim_products dp
        ON t.product_key = dp.product_key
    GROUP BY dp.product_number, dp.product_name
) t
WHERE rnk <= 5;

-- Top 10 customers with high revenue
SELECT c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount)
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY SUM(f.sales_amount) DESC
LIMIT 10;

-- Alternative
SELECT *
FROM (
    SELECT c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount),
           ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rnk
    FROM gold.dim_customers c
    LEFT JOIN gold.fact_sales f
        ON c.customer_key = f.customer_key
    GROUP BY c.customer_key, c.first_name, c.last_name
) t
WHERE rnk <= 10;

-- Least customers
SELECT *
FROM (
    SELECT c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount) AS revenue,
           ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount)) AS rnk
    FROM gold.dim_customers c
    LEFT JOIN gold.fact_sales f
        ON c.customer_key = f.customer_key
    GROUP BY c.customer_key, c.first_name, c.last_name
) t
WHERE rnk <= 10;

-- Customer with highest orders
SELECT *
FROM (
    SELECT c.customer_key, c.first_name, c.last_name, COUNT(f.order_number) AS orders,
           ROW_NUMBER() OVER(ORDER BY COUNT(f.order_number) DESC) AS rnk
    FROM gold.dim_customers c
    LEFT JOIN gold.fact_sales f
        ON c.customer_key = f.customer_key
    GROUP BY c.customer_key, c.first_name, c.last_name
) t
WHERE rnk <= 10;

-- Few orders
SELECT *
FROM (
    SELECT c.customer_key, c.first_name, c.last_name, COUNT(f.order_number) AS orders,
           ROW_NUMBER() OVER(ORDER BY COUNT(f.order_number)) AS rnk
    FROM gold.dim_customers c
    LEFT JOIN gold.fact_sales f
        ON c.customer_key = f.customer_key
    GROUP BY c.customer_key, c.first_name, c.last_name
) t
WHERE rnk <= 5;


GROUP BY order_year, order_month, order_day
ORDER BY order_year, order_month, order_day;
